const data = [
  {
    date: ['2020', 'Present'],
    industry: 'Healthcare',
    location: 'Chicago, IL',
    overview: 'Health solution and care delivery',
    position: 'Senior Software Engineer II',
    responsibilities: [
      'Lead the development and maintenance of complex React and React Native applications, ensuring scalability, performance, and a high-quality user experience',
      'Collaborated with backend engineers, and product teams, in order to ensure seamless integration and functionality, along with aiding in many areas of project and product management',
      'Conducted regular code reviews to ensure code quality, maintainability, and adherence to best practices while mentoring junior and mid-level developers, providing guidance on coding standards, troubleshooting, and problem-solving',
      'Worked closely with UX/UI to transform design concepts into functional, responsive, and user-friendly interfaces',
      'Maintained strong test coverage via Jest and various E2E testing tools to ensure code reliability and to reduce defects',
      'Enacted coding standards/style-guides for a more uniform codebase',
    ],
    slug: 'optum',
    title: ['Optum', 'Digital'],
    website: 'www.optum.com',
  },
  {
    date: ['2018', '2020'],
    industry: 'Healthcare',
    location: 'Chicago, IL',
    overview: 'Personalized data-driven health care',
    position: 'Senior Frontend Engineer',
    responsibilities: [
      'Created and implemented a robust RX and Pharmacy web app platform',
      'Worked closely with UX/UI to transform design concepts into functional, responsive, and user-friendly interfaces',
      'Collaborated with backend engineers, and product teams, in order to ensure seamless integration and functionality, along with aiding in many areas of project and product management',
    ],
    slug: 'rally-health',
    title: ['Rally', 'Health'],
    website: 'www.rallyhealth.com',
  },
  {
    date: ['2015', '2018'],
    industry: 'Tech',
    location: 'Chicago, IL',
    overview: 'Custom web design and development',
    position: 'Fullstack Engineer',
    responsibilities: [
      'Managed numerous AWS products for client websites including but not limited to EC2, RDS, S3, and SMS',
      'Built client web apps from the ground up using VueJS and AngularJS JavaScript frameworks, all while employing the latest web coding conventions',
      'Designed and managed API’s on Linux-based servers utilizing the PHP Laravel framework',
      'Coded custom deployment scripts in Ansible for CI/CD automation in order to ensure uniformity when releasing multiple products',
    ],
    slug: 'earlybird-co',
    title: ['Earlybird', 'Co'],
    website: null,
  },
  {
    date: ['2013', '2015'],
    industry: 'Events',
    location: 'Chicago, IL',
    overview: 'Experiential entertainment events',
    position: 'Web Developer',
    responsibilities: [
      'Helped oversee numerous concurrent projects for the various event websites',
      'Supported the ticketing/registration platform EventSprout built in CodeIgniter and then later in Laravel',
      'Managed and maintained RegistratioNATION website (precursor to EventSprout) via CodeIgniter',
    ],
    slug: 'red-frog-events',
    title: ['Red Frog', 'Events'],
    website: null,
  },
  {
    date: ['2012', '2013'],
    industry: 'Tech',
    location: 'Chicago, IL',
    overview: 'Custom web design and development',
    position: 'Junior Web Developer',
    responsibilities: [
      'Managed and maintained RegistratioNATION website in CodeIgniter for Red Frog Events',
      'Helped maintain the various custom-built event websites',
    ],
    slug: 'silverline-creative',
    title: ['Silverline', 'Creative'],
    website: null,
  },
];

export default data;
