import type { PrintFromDatabase } from '@/types';

const data: PrintFromDatabase[] = [
  {
    date: 'July, 2023',
    image: 'shop/prints/ad8f9626-62ba-4bfd-8675-c3531266631a.jpeg',
    location: 'Corsica',
    paymentLinks: [
      '8wM4hifxAdNKfMk5kI',
      '8wM5lm99caBy2Zy5kJ',
      '6oE9BC714gZWbw49B0',
    ],
    snippet: `The gateway to Conca on the last day of my 13 day southbound GR20 adventure, and the end of a beatifuly unique experience.`,
    tags: ['photograph', 'landscape'],
    title: 'Stone Gateway',
    uri: '/shop/gr20-gateway-in-corsica',
    year: '2023',
  },
  {
    date: 'November, 2019',
    image: 'shop/prints/6a35f76e-56a2-4e08-8f06-8efdb818981e.jpeg',
    location: 'Nepal',
    paymentLinks: [
      'eVa8xy1GK5he57GfYY',
      'cN25lm99cbFC6bK001',
      'cN2bJKgBEcJG7fO6oq',
    ],
    snippet: `A sunrise in the Himalayan mountains of Nepal taken from Annapurna Basecamp after finishing the Annapurna Circuit a couple of days earlier.`,
    tags: ['photograph', 'sunrise'],
    title: 'Basecamp Sunrise',
    uri: '/shop/annapurna-basecamp-sunrise',
    year: '2019',
  },
  {
    date: 'February, 2020',
    image: 'shop/prints/ee93e3d9-fd43-4d86-a01a-2c81f4cf5ef5.jpeg',
    location: 'Chile',
    paymentLinks: [
      'fZe7tu714dNKas07sv',
      '9AQ6pqadgcJG0Rq004',
      '6oEdRS5X04dacA84gl',
    ],
    snippet: `Morning on the second day of the "O" Circuit of Patagonia and I captured this picture of the mountains with tall grasses blowing in the wind.`,
    tags: ['photograph', 'landscape'],
    title: 'Fields of Serón',
    uri: '/shop/patagonia-seron',
    year: '2020',
  },
  {
    date: 'August, 2024',
    image: 'shop/prints/d95d97ce-2886-402a-85c7-dff926697bfd.jpeg',
    location: 'France',
    paymentLinks: [
      '14k29afxAgZWgQoeV0',
      '3cs29aadg10Y6bK5kr',
      '14k012fxAaBygQo6ow',
    ],
    snippet: `Taken on the second to last day of the Tour du Mont Blanc behind a mountain lake with the Mont Blanc range in the background.`,
    tags: ['photograph', 'landscape'],
    title: 'Mountain Lake',
    uri: '/shop/mont-blanc-mountain-lake',
    year: '2024',
  },
  {
    date: 'February, 2020',
    image: 'shop/prints/4d76b636-952a-44f0-afdd-947940c4e434.jpeg',
    location: 'Chile',
    paymentLinks: [
      'bIY012dpscJG0Rq4gp',
      'dR60122KO5he0Rq5ku',
      'bIY4hifxA6li9nW8wH',
    ],
    snippet: `I captured this picture of the morning sunrise light saturating the clouds around this mountain after a stormy night on the "O" Circuit in Chile.`,
    tags: ['photograph', 'sunrise'],
    title: 'Sunrise',
    uri: '/shop/patagonia-sunrise',
    year: '2020',
  },
  {
    date: 'July, 2019',
    image: 'shop/prints/bc6b66bb-28e0-4610-bf3a-43c1966c1762.jpeg',
    location: 'Italy',
    paymentLinks: [
      '9AQaFGclo10Y8jSaEQ',
      '3cs5lm2KOgZW43C7sF',
      'cN27tu5X09xu43CeV8',
    ],
    snippet: `The Dolomite mountains in northern Italy have some of the most unique formations I've ever seen, and this one is no exception.`,
    tags: ['photograph', 'mountains'],
    title: 'Dolomites',
    uri: '/shop/alta-via-mountain-throne',
    year: '2019',
  },
  {
    date: 'June, 2018',
    image: 'shop/prints/77a17efe-f203-4de9-b32f-6fc272b40109.jpeg',
    location: 'Spain',
    paymentLinks: [
      '9AQ6pq4SW8tqcA87sH',
      '4gw156adg396fMk7sI',
      '9AQ156etw7pmeIg9AR',
    ],
    snippet: `A long day, heading to Fromista along the Camino de Santiago.`,
    tags: ['photograph', 'landscape'],
    title: 'The Way',
    uri: '/shop/camino-de-santiago-fromista',
    year: '2018',
  },
  {
    date: 'June, 2023',
    image: 'shop/prints/0ff34736-949f-4981-b339-06b6d304ba51.jpeg',
    location: 'Corsica',
    paymentLinks: [
      'bIY8xy5X0252fMkbJ0',
      '6oEcNOetw6li8jS8wP',
      'cN26pq2KO10Y57GeVe',
    ],
    snippet: `One of the most beautiful sights in nature when the clouds form low to the ground, and you are hiking high above them.`,
    tags: ['photograph', 'clouds'],
    title: 'Cloud Inversion',
    uri: '/shop/cloud-inversion-in-corsica',
    year: '2023',
  },
  {
    date: 'December, 2022',
    image: 'shop/prints/24f59aee-4b5a-4857-a118-4a16f6de8927.jpeg',
    location: 'Egypt',
    paymentLinks: [
      '8wMbJK4SWcJGdEc5kF',
      '28oaFG5X0fVS57G6oK',
      'fZedRS5X02529nWdRd',
    ],
    snippet: `One of the seven ancient wonders of the world, the pyramids in Egypt at the Giza Plateau did not dissapoint`,
    tags: ['photograph', 'architecture'],
    title: 'Pyramid',
    uri: '/shop/pyramid-of-egypt',
    year: '2022',
  },
];

export default data;
